import { Container, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from './auth/Provider';
import './globals.css';
import NavBar from './NavBar';
import QueryClientProvider from './QueryClientProvider';
import './theme-config.css';


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Issue Tracker App',
  description: 'Generated by gootibi developer with NextJs',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        {/* Use React Query - query client contains a cache for storing data we get from the backend  */}
        <QueryClientProvider>
          {/* Add AuthAdapter - /app/auth/Provider.tsx */}
          <AuthProvider>
            <Theme appearance="light" accentColor="iris">
              <NavBar />
              <main className='p-5'>
                <Container>{children}</Container> {/* Raidix-ui <Container> -> applies a max width to our page and puts the content in the center */}
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
