import { Container, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from './NavBar';
import './theme-config.css';
import AuthProvider from './auth/Provider';


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Issue Tracker App',
  description: 'Generated by gootibi developer with NextJs',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        {/* Add AuthAdapter - /app/auth/Provider.tsx */}
        <AuthProvider> 
          <Theme appearance="light" accentColor="iris">
            <NavBar />
            <main className='p-5'>
              <Container>{children}</Container> {/* Raidix-ui <Container> -> applies a max width to our page and puts the content in the center */}
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
